apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
      - image: okteto/go-getting-started:hello-world
        name: billing

---

apiVersion: v1
kind: Service
metadata:
  name: billing
spec:
  type: ClusterIP
  ports:
  - name: "billing"
    port: 8080
  selector:
    app: billing

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: billing
  annotations:
    dev.okteto.com/generate-host: billing
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: billing
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
